version: '3.9'
services:
  backend:
    restart: always
    command : python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
