# Generated by Django 4.0.4 on 2022-10-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(default='2001-01-01', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default='2001-01-01', verbose_name='Start date'),
        ),
    ]
